sudo: required
services:
  - docker

before_install:
    - docker build -t frankallan7/frontend -f Dockerfile.dev . 

script:
    - docker run -e CI=true frankallan7/frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "devo"
  bucket_name: "elasticbeanstalk-us-west-2-157234150582"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
